#!/usr/bin/env bash

set -Eeufo pipefail

echo --- :git: Testing if commit is an ancestor of the branch

git fetch origin '*:*'

git show-ref

git merge-base --is-ancestor "$BUILDKITE_COMMIT" "refs/remotes/origin/$BUILDKITE_BRANCH"
